swagger: "2.0"
info:
  description: The swagger file for the API
  version: "1.0.0"
  title: YouTube Spam API
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: /api

definitions:
  PredictRequestBody:
    type: array
    items:
      type: string
      description: YouTube comment to classify
      example: "sample comment here"

paths:
  /predict:
    post:
      operationId: "spam_classifier.predict"
      tags:
        - "spam_classifier"
      summary: "YouTube comments Spam Classifier Prediction Endpoint using various algorithms"
      description: "Generate spam or not spam predictions based on the input comment"
      parameters:
        - in: body
          name: body
          description: "Required array of string comments in the request payload"
          required: true
          schema:
            $ref: "#/definitions/PredictRequestBody"
      responses:
        200:
          description: "success"
          schema:
            type: object
            properties:
              predictions:
                type: array
                description: "integer values indicating spam (1) or not spam (0)"
                items:
                  type: integer
                  example: 1
            required:
              - predictions
        400:
          description: "prediction failed"
          schema:
            type: object
            properties:
              message:
                type: string
                example: "prediction failed :("
